### ISSUE TITLE
Missing MAP file

### ISSUE THREAD

**Issue by simonbretin** [aljosamrak/OpenHab-OpenWeatherMap-transform#1]
Hello,
Very nice projet. 
However seems like you forgot the openweathermap.map file that is being referenced for the .items file. 
Looks like the file will be something like :
01d=sky is clear
02d=few clouds
03d=scattered clouds
...
Could you confirm ? 
Thanks,
Simon.

**Comment by aljosamrak** [comment]
Hello.
You are right. I forgot to commit it. Now it should be there. If there are any other problems, please contact me.

**Comment by simonbretin** [comment]
Thanks for the confirmation !
